---
version: "3.7"
services:
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic
    
    ports:
      - ${AIRSONIC_PORT}:4040
    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - CONTEXT_PATH=<URL_BASE> #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
      - ${CONFIGDIR}airsonic:/config
      - ${ADULTAUDIOS}:/data/music

    restart: unless-stopped