---
version: "3"
services:
  airsonic:
    image: lscr.io/linuxserver/airsonic
    container_name: airsonic
    
    ports:
      - ${AIRSONIC_PORT}:4040
    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - CONTEXT_PATH=<URL_BASE> #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
      - ${CONFIGDIR}airsonic:/config
      - ${AUDIOS}:/data/music

  restart: unless-stopped

  config:
    