---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.eja.net.au
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=T00woomb@
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/console/config/bookstack/app:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=T00woomb@
      - TZ=Australia/Brisbane
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=T00woomb@
    volumes:
      - /home/console/config/bookstack/db:/config
    restart: unless-stopped