version: '3'
services:
  dupeguru:
    image: jlesage/dupeguru
    ports:
      - ${DG_PORT}:5800
    volumes:
      - ${CONFIGDIR}dupeguru:/config
      - ${ADULT_SCENES}:/adultscenes
      - ${ADULT_MOVIES}:/adultmovies