---
version: "3.8"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ${CONFIGDIR}duplicati:/config
      - ${DATADIR}backups:/backups
      - ${SOURCEDIR}:/source
    ports:
      - ${DUPE_PORT}:8200
    restart: unless-stopped