---
version: "3"
services:
  emby:
    image: lscr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}emby:/config
      - ${INTERACTIVE}:/data/interactive
      - ${ADULTSCENES}:/data/adultscenes
      - ${ADULTMOVIES}:/data/adultmovies
      - ${OF}:/data/onlyfans
      - ${DOWNLOADS}:/unsorted
      - ${AMATEUR}:/data/amateur
      - ${HENTAI}:/data/hentai
    # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - ${EMBY_PORT}:8096
    #  - 8920:8920 #optional
    #devices:
    #  - /dev/dri:/dev/dri #optional
    #  - /dev/vchiq:/dev/vchiq #optional
    #  - /dev/video10:/dev/video10 #optional
    #  - /dev/video11:/dev/video11 #optional
    #  - /dev/video12:/dev/video12 #optional
    restart: unless-stopped