---
version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}heimdall:/config
    ports:
      - ${HEIMDALLHTTP}:80
      - ${HEIMDALLHTTPS}:443
    restart: unless-stopped