version: '3.8'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    ports:
      - target: ${HBPORT}
        published: ${HBPORT}
        protocol: tcp
        mode: overlay
    volumes:
      - ${CONFIGDIR}homebridge:/homebridge