---
version: "3"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONDIGDIR}homeassistant:/config
    ports:
      - ${HA_PORT}:8123
#    devices:
#      - /path/to/device:/path/to/device
    restart: unless-stopped