version: '3'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - ${HB_PORT}=8581
    volumes:
      ${CONFIGDIR}homebridge:/homebridge