---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /home/console/config/homeassistant:/config
    ports:
      - 8123:8123
#    devices:
#      - /path/to/device:/path/to/device
    restart: unless-stopped