---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/console/config/jackett:/config
      - /home/console/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped