---
version: "3.7"
services:
  jackett:
    image: cr.hotio.dev/hotio/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ${CONFIGDIR}jackett:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - ${JACKETT_PORT}:9117
    restart: unless-stopped