version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - /home/console/config/jdownloader:/config:rw
      - /home/console/media/unsorted:/output:rw