---
version: "3.8"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    #container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=${KASM_PORT}
      - TZ=${TZ}
      #- DOCKER_HUB_USERNAME=USER #optional
      #- DOCKER_HUB_PASSWORD=PASS #optional
    volumes:
      - ${CONFIGDIR}kasm:/opt
      - ${DATADIR}kasm/profiles:/profiles #optional
    ports:
      - ${KASM_INIT}:3000
      - ${KASM_PORT}:443
    restart: unless-stopped