---
version: "3.7"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
#      - MYSQL_DATABASE=USER_DB_NAME #optional
#      - MYSQL_USER=MYSQL_USER #optional
#      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      - REMOTE_SQL=https://sql.${DOMAIN} #optional
    volumes:
      - ${CONFIGDIR}mariadb:/config
      - ${MARIADBDIR}:/db
    ports:
      - 3306:3306
    restart: unless-stopped