version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - ${NPM_HTTP}:80
      - ${NPM_MGMT}:81
      - ${NPM_HTTPS}:443
    volumes:
      - ${CONFIGDIR}/npm:/data
      - ${CERTSDIR}/letsencrypt:/etc/letsencrypt
