---
version: "3.8"
services:
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - BASE_URL=/ombi #optional
    volumes:
      - ${CONFIGDIR}ombi:/config
    ports:
      - ${OMBI}:3579
    restart: unless-stopped