---
version: "3"
services:
  duplicati:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FPM=true
      - branch=v2-master
    volumes:
      - ${CONFIGDIR}organizr:/config
    ports:
      - ${ORGANIZR}:80
    restart: unless-stopped