version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - target: ${DNS_PORT}
        published: ${DNS_PORT}
        protocol: tcp
        mode: host
      - target: ${DNS_PORT}
        published: ${DNS_PORT}
        protocol: udp
        mode: host
      - target: ${DNS_REP_PORT}
        published: ${DNS_REP_PORT}
        protocol: udp
        mode: host
    environment:
      TZ: ${TZ}
      WEBPASSWORD: '${PASSWORD}'
    # Volumes store your data between container upgrades
    volumes:
      - '${CONFIGDIR}/pihole:/etc/pihole/'
      - '${DNSMASQ}:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    networks:
      - pihole
    restart: unless-stopped

networks:
  pihole:
    external: true
