---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-tixke-pjT9cVg44FvWzU #optional
    volumes:
      - /home/console/config/plex:/config
      - /home/console/media/tv:/tv
      - /home/console/media/movies:/movies
      - /home/console/temp:/transcode
    restart: unless-stopped