---
version: "3"
services:
  plex:
    image: cr.hotio.dev/hotio/plex
    container_name: plex
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}plex:/config
      - ${TV}:/tv
      - ${MOVIES}:/movies
      - ${TRANSCODE}:/transcode

    
      
    restart: unless-stopped