version: '3.5'

services:
  postgres:
    #container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${DBDIR}postgres
    volumes:
      - ${DBDIR}postgres:/data/postgres
    ports:
      - "${PG_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    #container_name: pgadmin_db
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE: 'False'
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: overlay

