---
version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBA}
    volumes:
      - ${CONFIGDIR}qb-adult:/config
      - ${DOWNLOADS}:/downloads
      - ${ADULTSCENES}:/adultscenes
      - ${ADULTMOVIES}:/adultmovies
      - ${AMATEUR}:/amateur
      - ${INTERACTIVE}:/interactive
      - ${ADULTGAMES}:/games
      - ${OF}:/onlyfans
    ports:
      - 6881:6881
      - 6881:6881/udp
      - ${QBA}:8080
    restart: unless-stopped