---
version: "3.7"
services:
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QB}
    volumes:
      - ${CONFIGDIR}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
      - ${TV}:/tv
      - ${MOVIES}:/movies
      - ${GAMES}:/games
#      - /home/console/media/comics:/comics
    ports:
      - ${QB}:8080
    restart: unless-stopped