---
version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QB_PORT}
    volumes:
      - ${CONFIGDIR}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
      - ${TV}:/tv
      - ${MOVIES}:/movies
#      - /home/console/media/games:/games
#      - /home/console/media/comics:/comics
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped