---
version: "3.7"
services:
  radarr:
    image: cr.hotio.dev/hotio/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}radarr:/config
      - ${MOVIES}:/movies #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - ${RADARR}:7878
    restart: unless-stopped