---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /home/console/config/radarr:/config
      - /home/console/media/movies:/movies #optional
      - /home/console/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped