version: "3"
services:
  rmd:
    image: shadowmoose/redditdownloader
    container_name: rmd
    ports:
      - ${RMD_PORT}:7505/tcp
    volumes:
      - ${ADULTAUDIOS}:/download
      - ${CONFIGDIR}rmd:/base
    restart: unless-stopped