---
version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}sonarr:/config
      - ${TV}:/tv #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped