version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Australia/Brisbane
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267
    volumes:
      - /home/console/config/tdarr/server:/app/server
      - /home/console/config/tdarr/configs:/app/configs
      - /home/console/config/tdarr/logs:/app/logs
      - /home/console/media/movies:/movies
      - /home/console/media/tv:/tv
      - /home/console/media/adult:/adult
      - /home/console/cache:/temp