---
version: "3.8"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${VSCODE_PASSWORD} #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=vscode.eja.net.au #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/console/config/vscode:/config
    ports:
      - 3443:8443
    restart: unless-stopped